### ISSUE TITLE
UnrecognizedPropertyException: Unrecognized field "config.metrics" with Spinnaker version 1.21.3

### ISSUE THREAD

**Issue by matiwari** [armory-plugins/armory-observability-plugin#23]
I am trying to use https://github.com/armory-plugins/armory-observability-plugin#plugin-configuration  with prometheus, we are running spinnaker version  1.21.3 with Operator based installation.

i have added required configuration for enabling plugin in SpinnakerService.yaml file 
**spinnaker:
        extensibility:
          plugins:
            Armory.ObservabilityPlugin:
              config.metrics:
                additionalTags:
                  customerEnvName: test
                  customerName: testcust
                prometheus:
                  enabled: true
                  meterRegistryConfig.armoryRecommendedFiltersEnabled: true
              enabled: true
          repositories:
            armory-observability-plugin-releases:
              url: https://raw.githubusercontent.com/armory-plugins/armory-observability-plugin-releases/master/repositories.json**

It should add plugin Ideally  but we are getting exception in operator :
`com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "config.metrics" (class com.netflix.spinnaker.halyard.config.model.v1.plugins.Plugin), not marked as ignorable (5 known properties: "version", "enabled", "id", "extensions", "uiResourceLocation"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["spinnaker"]->com.netflix.spinnaker.halyard.config.model.v1.node.Spinnaker["extensibility"]->com.netflix.spinnaker.halyard.config.model.v1.node.Extensibility["plugins"]->java.util.LinkedHashMap["Armory.ObservabilityPlugin"]->com.netflix.spinnaker.halyard.config.model.v1.plugins.Plugin["config.metrics"])`

I tried adding version for plugin 1.0.0 as well but same exception 

Is plugin not supportable with 1.21.3 ?  Or Any suggestion please  if i am missing or doing anything wrong ?

**Comment by jasonmcintosh** [comment]
https://github.com/armory-plugins/armory-observability-plugin/issues/21
Looks like the same issue FYI - halyard is still used by operator under the hood...

**Comment by matiwari** [comment]
i tried splitting the config.metrics as you mentioned in #21  but still did not works

**Comment by fieldju** [comment]
Until the PR gets released all the way through the halyard / operator chain you have to use a global profile for spinnaker
https://gist.github.com/fieldju/670c1696d202ebd211876eff99ec45f5#file-microk8s-dev-yaml-L101

**Comment by fieldju** [comment]
Clones https://github.com/armory-plugins/armory-observability-plugin/issues/21
