### ISSUE TITLE
NaN Values on some JVM metrics

### ISSUE THREAD

**Issue by jasonmcintosh** [armory-plugins/armory-observability-plugin#32]
Seeing NaN reported for several metric values... 
Example:
`
Element | Value
-- | --
jvm_memory_used{app_kubernetes_io_name="clouddriver",armSpinSvcVer="2.22.11",container="clouddriver",customerEnvName="testing",customerName="jasonmcintosh",endpoint="7002",id="CodeHeap 'non-nmethods'",instance="10.1.15.14:7002",job="clouddriver",lib="aop",libVer="v1.1.3",memtype="NON_HEAP",namespace="spinnaker",ossSpinSvcVer="6.11.1-20201012160101",pod="spin-clouddriver-8878c977b-nnxjm",spinSvc="clouddriver",spinnakerRelease="1.22.2",version="6.11.1-20201012160101"} | NaN

`

**Comment by jasonmcintosh** [comment]
I'm pretty strongly suspicious that this is something in micrometer:
https://github.com/micrometer-metrics/micrometer/issues/2279
SO I think this may be just because there are different metric names for JVM memory and some that are referenced and then GC'd.

**Comment by jasonmcintosh** [comment]
Apparently what happens is micrometer uses jvm.memory.used, but SPRING uses jvm.memory.used.bytes from the research done thus far.  I'd THINK we should actually filter out jvm_memory_used (e.g. jvm.memory.used by id) in favor of the spring native ones.  I'd suspect we see this as a result of ACTUALLY integrating more fully with micrometer & spring vs. the monitoring daemon translating spectator.  FYI @kskewes
this likely would affect other dashboards/usage.  Wondering if this is consistent across all the services.

**Comment by jasonmcintosh** [comment]
Note, still digging - Orca DOES still use jvm_memory_used.  I need to see if there's a library mismatch or something else goofy going on.  I think this might be a case where some services are mis-matched on library versions.

**Comment by kskewes** [comment]
Nice sleuthing.
IIRC it's only Orca that seems to be doing something different. Away from computer but can check next week..

**Comment by jasonmcintosh** [comment]
Meh, not sure it's great sleuthing YET... still digging into what's going on.  LOCALLY, at least core metrics don't seem duplicated, but I need to actually trigger some behavior to see what's going on - I've got a pretty solid idea what's up but need to get tracing going ;)

**Comment by battlecow** [comment]
Anyone been able to pin down what needs to change on Orca for jvm metrics?

**Comment by christosarvanitis** [comment]
Started to looking into this:
``` 
% curl -s spin-orca.spinnaker:8083/aop-prometheus | grep jvm | grep TYPE | sort 
# TYPE jvm_buffer_count gauge
# TYPE jvm_buffer_memoryUsed gauge
# TYPE jvm_gc_allocationRate_total counter
# TYPE jvm_gc_liveDataSize gauge
# TYPE jvm_gc_maxDataSize gauge
# TYPE jvm_gc_pause_seconds summary
# TYPE jvm_gc_pause_seconds_max gauge
# TYPE jvm_gc_promotionRate_total counter
# TYPE jvm_memory_committed gauge
# TYPE jvm_memory_max gauge
# TYPE jvm_memory_used gauge

% curl -s spin-clouddriver.spinnaker:7002/aop-prometheus | grep jvm  | grep TYPE | sort 
# TYPE jvm_buffer_count_buffers gauge
# TYPE jvm_buffer_memoryUsed gauge
# TYPE jvm_buffer_memory_used_bytes gauge
# TYPE jvm_buffer_total_capacity_bytes gauge
# TYPE jvm_classes_loaded_classes gauge
# TYPE jvm_classes_unloaded_classes_total counter
# TYPE jvm_gc_allocationRate_total counter
# TYPE jvm_gc_liveDataSize gauge
# TYPE jvm_gc_live_data_size_bytes gauge
# TYPE jvm_gc_maxDataSize gauge
# TYPE jvm_gc_max_data_size_bytes gauge
# TYPE jvm_gc_memory_allocated_bytes_total counter
# TYPE jvm_gc_memory_promoted_bytes_total counter
# TYPE jvm_gc_pause_seconds summary
# TYPE jvm_gc_pause_seconds_max gauge
# TYPE jvm_gc_promotionRate_total counter
# TYPE jvm_memory_committed gauge
# TYPE jvm_memory_committed_bytes gauge
# TYPE jvm_memory_max gauge
# TYPE jvm_memory_max_bytes gauge
# TYPE jvm_memory_used gauge
# TYPE jvm_memory_used_bytes gauge
# TYPE jvm_threads_daemon_threads gauge
# TYPE jvm_threads_live_threads gauge
# TYPE jvm_threads_peak_threads gauge
# TYPE jvm_threads_states_threads gauge


carvanitis@Christoss-MacBook-Pro armory-observability-plugin % curl -s spin-front50.spinnaker:8080/aop-prometheus | grep jvm  | grep TYPE | sort 
# TYPE jvm_buffer_count_buffers gauge
# TYPE jvm_buffer_memoryUsed gauge
# TYPE jvm_buffer_memory_used_bytes gauge
# TYPE jvm_buffer_total_capacity_bytes gauge
# TYPE jvm_classes_loaded_classes gauge
# TYPE jvm_classes_unloaded_classes_total counter
# TYPE jvm_gc_allocationRate_total counter
# TYPE jvm_gc_liveDataSize gauge
# TYPE jvm_gc_live_data_size_bytes gauge
# TYPE jvm_gc_maxDataSize gauge
# TYPE jvm_gc_max_data_size_bytes gauge
# TYPE jvm_gc_memory_allocated_bytes_total counter
# TYPE jvm_gc_memory_promoted_bytes_total counter
# TYPE jvm_gc_pause_seconds summary
# TYPE jvm_gc_pause_seconds_max gauge
# TYPE jvm_gc_promotionRate_total counter
# TYPE jvm_memory_committed gauge
# TYPE jvm_memory_committed_bytes gauge
# TYPE jvm_memory_max gauge
# TYPE jvm_memory_max_bytes gauge
# TYPE jvm_memory_used gauge
# TYPE jvm_memory_used_bytes gauge
# TYPE jvm_threads_daemon_threads gauge
# TYPE jvm_threads_live_threads gauge
# TYPE jvm_threads_peak_threads gauge
# TYPE jvm_threads_states_threads gauge
```

NaN values appear on for all services:
- jvm_memory_max
- jvm_memory_committed
- jvm_memory_used
- jvm_buffer_count
- jvm_buffer_memoryUsed

At the same time Orca doesnt report the same JVM metrics as the rest of services. I think we may have 2 issues here? 
- Orca doesnt report the same JVM metrics as the rest of the services (missing metrics)
- And the micrometer issue @jasonmcintosh mentioned above

**Comment by christosarvanitis** [comment]
@jasonmcintosh @kskewes Managed to track down the bug(?) in Orca. So coming from [here](https://github.com/spinnaker/orca/blob/master/orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/telemetry/SpectatorHikariMetricsTrackerFactory.kt). 

The Orca sql pool stats for spectator is using the Hikari library which requires PrometheusMeterRegistry. So there is an early instantiated of the Bean causing the Observability plugin not to register the metrics.

Seems a poor implementation on Orca side but will try to see if we can handle a fix in the Observability plugin. This will resolve also https://github.com/armory-plugins/armory-observability-plugin/issues/33

**Comment by massimo-pacher-tw** [comment]
I think there are 2 issues which are mixed up here:
1. Spectator metrics result in NaN cause holding weak references and being GCed
2. Micrometer metrics (e.g. JVM, logback,etc are NOT exported)

1 is a common issue across all the spinnaker services, which we fixed for some relevant cases (e.g Igor)
2 instead, as mentioned above, is limited to Orca, and we noticed cause some of our common dashboards were empty.

The most visible example of 2 for me was the JVM metrics ones:
- `jvm_memory_used` --> NaN
- `jvm_memory_used_bytes` (micrometer) was just not there

I manage to fix the issue on Orca in our fork: as @christosarvanitis correctly mentioned, the child classes of `AbstractMetricsPostProcessor` are preventing `ArmoryObservabilityCompositeRegistry` to be processed by Spring `MeterRegistryPostProcessor`: these means no micrometer binders are attached to the registry.

There's a warning log which describe the issue:

```
'io.armory.plugin.observability.registry.ArmoryObservabilityCompositeRegistry' of type [io.armory.plugin.observability.registry.ArmoryObservabilityCompositeRegistry] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

The culprit is the `@Autowired` the child classes: https://github.com/spinnaker/orca/blob/master/orca-core/src/main/java/com/netflix/spinnaker/orca/telemetry/ThreadPoolMetricsPostProcessor.java#L34

As per Spring `Autowired` doc:

```
Note that actual injection is performed through a BeanPostProcessor which in turn means that you cannot use @Autowired to inject references into BeanPostProcessor or BeanFactoryPostProcessor types.
```
So, without changing the design (e.g. moving away from a BeanPostProcessor or from an abstract class), a simple `@Lazy` on all the 3 child classes will make the trick.

Example:

``` 
  @Autowired
  @Lazy
  public ThreadPoolMetricsPostProcessor(Registry registry) {
    super(ThreadPoolTaskExecutor.class, registry);
  }
```

I can submit a PR on orca with the fix as well, cause I think Orca is abusing of the dependency injection in this scenario 😄 
But if you have a fork, try it out.

**Comment by massimo-pacher-tw** [comment]
@dbyron-sf here it is: https://github.com/spinnaker/orca/pull/4224

As you can see, it might need Kayenta to be bumped too.

**Comment by jasonmcintosh** [comment]
@massimo-pacher-tw HUGE thank you for fixing these :) We'd known about it, but we run APM agents for most core JVM metrics, so we'd not spent much time trying to fix OSS other than "Yep it's something in the bean handling" layer.

**Comment by dbyron-sf** [comment]
More thanks for @massimo-pacher-tw here as well!  This is a very big help!

**Comment by kskewes-sf** [comment]
This is great, thanks @massimo-pacher-tw 

Also closes out: https://github.com/armory-plugins/armory-observability-plugin/issues/33
