### ISSUE TITLE
DataDog support

### ISSUE THREAD

**Issue by jgrumboe** [armory-plugins/armory-observability-plugin#36]
Hi,
Could you also support DataDog as target like Newrelic?
There's existing DataDog support in the micrometer project https://github.com/micrometer-metrics/micrometer/tree/master/implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog
Best regards,
Johannes

**Comment by jasonmcintosh** [comment]
So would welcome it and PR's to add support ;). It's been on the backlog to add but we don't have an ETA.

A common work around is to use DataDog's open metrics scraper to autodiscover & scrape services since often you'll have the agent installed into where-ever spinnaker is running.

**Comment by christosarvanitis** [comment]
The support for Datadog has been merged into the default branch. We will release a new version v1.4.0
