### ISSUE TITLE
Listening Port - Prevent exposing Spinnaker internal API's to Prometheus

### ISSUE THREAD

**Issue by kskewes** [armory-plugins/armory-observability-plugin#5]
## Summary

Exposing Prometheus metrics on the same `port` but a different `path` to a Spinnaker services API endpoint is simple.
However it exposes a services internal API's potentially unauthenticated to Prometheus system and the operators of Prometheus.

If Prometheus is compromised then an attacker could leverage Prometheus' service discovery abilities to find Spinnaker endpoints and access say `Fiat` service to modify permissions.

Prometheus acts like `Everyone Else` in diagrams here: https://spinnaker.io/setup/security/authorization/#requirements

## Solution

Personally prefer a different port by default, convention over configuration.
Simpler for example Prometheus configuration files, issues, etc.

Avoid collision with:

- [Spinnaker port-mappings](https://spinnaker.io/reference/architecture/#port-mappings)
- other possible services on host (non container installs) - [Wiki Ports](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers)

Process: 

1. Pick a Prometheus Exporter port from [Prometheus Default Allocations](https://github.com/prometheus/prometheus/wiki/Default-port-allocations), eg: `9710` (I'm happy to PR this if acceptable)
2. Add an `Endpoint` with a Custom Port - eg revert?: https://github.com/armory-plugins/armory-observability-plugin/commit/53fed008bdb87b4c66f3acc119d3e37dd3d8d31f (`/prometheus` path is good too but anything ok)
3. Add example Prometheus scrape config (YAML) & `PodMonitor` to suit this port (I'm happy to PR this if acceptable)

**Comment by fieldju** [comment]
@kskewes re: `Personally prefer a different port by default, convention over configuration.`

☝️ My PR does *NOT* do that, it is utilizing Springboots Actuator system, just like the official Micrometer Registry does.

You will have to configure it like so

https://gist.github.com/fieldju/7722f36451a652c399db182765046fd3#file-observability-yaml-L20-L24

The good news is that you only have to configure it in spinnaker-local.yml and it can be applied globally.

**Comment by fieldju** [comment]
I origionally just wanted to include this https://github.com/spring-projects/spring-boot/blob/cd1baf18fe9ec71c11d7d131d6f1a417ec0c00e2/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/export/prometheus/PrometheusScrapeEndpoint.java in the plugin.

But for some reason using the `@WebEndpoint` in a plugin bean does weird things with the Pf4j class loader and you get no class def errors.

CC: @claymccoy @link108 ☝️ 

Luckily I found out today that you can use the alternative annotation `@Endpoint` and hook into the actuator system from a plugin.

**Comment by kskewes** [comment]
>  My PR does NOT do that, it is utilizing Springboots Actuator system, just like the official Micrometer Registry does.

Having the ability to change the port satisfies the network separation/firewall use case so thanks very much for that.
